version: 2
updates:
  - package-ecosystem: composer
    directory: "/"
    schedule:
      interval: weekly
      timezone: America/Los_Angeles
      day: monday
    target-branch: main
    open-pull-requests-limit: 99
    commit-message:
      prefix: "[composer]"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    target-branch: main
    commit-message:
      prefix: "[gha]"