name: Deploy to Pantheon

on:
  push:
    branches:
      - main

permissions:
  contents: write
  deployments: write
  statuses: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Composer dependencies
        run: composer install

      - name: Push to Pantheon
        uses: stevector/push-to-pantheon@checkout_repo
        with:
          ssh_key: ${{ secrets.SSH_KEY }}
          site: cxr-dtp-test
          machine_token: ${{ secrets.TERMINUS_TOKEN }}
          target_env: dev
          checkout_repo: false