name: Deploy to Pantheon

on:
  push:
    branches:
      - main
    paths-ignore:
      - .github/**
      - README.md

permissions:
  contents: write
  deployments: write
  statuses: write

jobs:
  deploy:
    name: Push to Pantheon
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure SSH
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Configure Pantheon Host Key
        run: |
          echo "Host *.drush.in HostKeyAlgorithms +ssh-rsa" >> ~/.ssh/config
          echo "Host *.drush.in PubkeyAcceptedKeyTypes +ssh-rsa" >> ~/.ssh/config
          echo "StrictHostKeyChecking no" >> ~/.ssh/config

      - name: Pull from Pantheon
        run: |
          git clone ssh://codeserver.dev.${{secrets.SITE_ID}}@codeserver.dev.${{secrets.SITE_ID}}.drush.in:2222/~/repository.git pantheon-repo
          echo "Syncing Pantheon repo with GitHub..."
          rsync -a --ignore-existing --exclude='.git' pantheon-repo/ ./
          rm -rf pantheon-repo/

      - name: Composer dependencies
        run: composer install

      - name: Push to Pantheon
        uses: stevector/push-to-pantheon@0.4.0
        id: deploy
        with:
          ssh_key: ${{ secrets.SSH_KEY }}
          site: cxr-dtp-test
          machine_token: ${{ secrets.TERMINUS_TOKEN }}
          target_env: dev
  
      - name: Install Node.js
        if: ${{ steps.deploy.outcome == 'success' }}
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Playwright
        run: |
          npm install -D playwright
          npx playwright install --with-deps

      - name: Run Playwright test
        env:
          BASE_URL: https://dev-cxr-dtp-test.pantheonsite.io
        run: npx playwright test tests/postDeploy.spec.ts
  