name: Deploy to Pantheon

on:
  push:
    branches:
      - main

permissions:
  contents: write
  deployments: write
  statuses: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Pull from Pantheon
        run: |
          git clone sh://codeserver.dev.${{secrets.SITE_ID}}@codeserver.dev.${{secrets.SITE_ID}}.drush.in:2222/~/repository.git pantheon-repo
          rsync -a --ignore-existing --exclude='.git' pantheon-repo/ ./
          rm -rf pantheon-repo/

      - name: Composer dependencies
        run: composer install

      - name: Push to Pantheon
        uses: stevector/push-to-pantheon@checkout_repo
        with:
          ssh_key: ${{ secrets.SSH_KEY }}
          site: cxr-dtp-test
          machine_token: ${{ secrets.TERMINUS_TOKEN }}
          target_env: dev
          checkout_repo: false