name: Test

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Playwright Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Playwright
        run: |
          npm install -D playwright @playwright/test
          npx playwright install

      - name: Install Terminus
        uses: pantheon-systems/terminus-github-actions@v1
        with:
          pantheon-machine-token: ${{ secrets.TERMINUS_TOKEN }}

      - name: Wait for Pantheon build to complete
        run: terminus workflow:wait cxr-dtp-test.dev --max=30

      - name: Run Playwright test
        env:
          BASE_URL: https://dev-cxr-dtp-test.pantheonsite.io
        run: npx playwright test "${{ github.workspace }}/.github/tests/postDeploy.spec.ts"