name: Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Playwright
        run: |
          npm install -D playwright
          npx playwright install --with-deps

      - name: Run Playwright test
        env:
          BASE_URL: https://dev-cxr-dtp-test.pantheonsite.io
        run: npx playwright test ../tests/postDeploy.spec.ts